name: Python3.9 pytest
# do not change name
on: 
  push:
    branches:
    - master
    - dev
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics    
    
    - name: test create shinx docs
      # create shpinx api autodocs of rlskyjo and move them to docs
      # makefile: make html build the the docs/_build/html/
      run: |
        sphinx-apidoc -o ./docs ./rlskyjo
        cd docs
        make html

    - name: Generate Report
      run: |
        coverage run -m --source=./rlskyjo pytest tests 
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2